## Configuration options for the base intermediate schema generator
##
## After modifying this file, regenerate the base intermediate schema
## by running the `generate_schema` script

output_directory: ../common/intermediate_db_schema
output_filename: 000_base_schema.sql

## Tables to include in the generated base intermidate schema.
##
## Available table options:
## ignore:      List of columns to ingore
## primary_key: Literal or list of columns to use as primary
## extend:      A list of objects describing new columns to added. Add a new column
##              or transform an existing one
## indexes:     List of indexes to create
tables:
  users:
    ignore:
      - seen_notification_id
      - last_posted_at
      - password_hash
      - salt
      - active
      - last_emailed_at
      - approved_by_id
      - previous_visit_at
      - suspended_at
      - suspended_till
      - views
      - flag_level
      - ip_address
      - title
      - uploaded_avatar_id
      - locale
      - primary_group_id
      - first_seen_at
      - silenced_till
      - group_locked_trust_level
      - manual_locked_trust_level
      - secure_identifier
      - flair_group_id
      - last_seen_reviewable_id
      - password_algorithm
      - username_lower
    extend:
      - name: email
      - name: created_at
        "null": true  # TODO: Ugly fix, perhaps is_null??
      - name: staged
        "null": true
      - name: avatar_path
      - name: avatar_url
      - name: avatar_upload_id
      - name: bio
      - name: password
        "null": true
      - name: trust_level
        "null": true
      - name: suspension
      - name: location
      - name: website
      - name: old_relative_url
      - name: sso_record
      - name: anonymized
        type: boolean
      - name: original_username
      - name: timezone
      - name: email_level
        type: integer
      - name: email_messages_level
        type: integer
      - name: email_digests
        type: boolean
  categories:
    ignore:
      - topic_id
      - topic_count
      - user_id
      - topics_year
      - topics_month
      - topics_week
      - auto_close_hours
      - post_count
      - latest_post_id
      - latest_topic_id
      - posts_year
      - posts_month
      - posts_week
      - email_in
      - email_in_allow_strangers
      - topics_day
      - posts_day
      - allow_badges
      - name_lower
      - auto_close_based_on_last_post
      - topic_template
      - contains_messages
      - sort_order
      - sort_ascending
      - uploaded_logo_id
      - uploaded_background_id
      - topic_featured_link_allowed
      - all_topics_wiki
      - show_subcategory_list
      - num_featured_topics
      - default_view
      - subcategory_list_style
      - default_top_period
      - mailinglist_mirror
      - minimum_required_tags
      - navigate_to_first_post_after_read
      - search_priority
      - allow_global_tags
      - reviewable_by_group_id
      - read_only_banner
      - default_list_filter
      - allow_unlimited_owner_edits_on_first_post
      - default_slow_mode_seconds
      - uploaded_logo_dark_id
      - uploaded_background_dark_id
    extend:
      - name: about_topic_title
      - name: old_relative_url
      - name: existing_id
        type: integer
      - name: permissions
        type: json_text # JSON_TEXT ???
      - name: logo_upload_id
      - name: tag_group_ids
        type: json_text # JSON_TEXT ???
  topics:
    ignore:
      - last_posted_at
      - posts_count
      - last_post_user_id
      - reply_count
      - featured_user1_id
      - featured_user2_id
      - featured_user3_id
      - featured_user4_id
      - deleted_at
      - highest_post_number
      - like_count
      - incoming_link_count
      - moderator_posts_count
      - bumped_at
      - has_summary
      - archetype
      - notify_moderators_count
      - spam_count
      - score
      - percent_rank
      - slug
      - deleted_by_id
      - participant_count
      - word_count
      - excerpt
      - fancy_title
      - highest_staff_post_number
      - featured_link
      - reviewable_score
      - image_upload_id
      - slow_mode_seconds
      - bannered_until
      - external_id
    extend:
      - name: old_relative_url
      - name: private_message
  posts:
    ignore:
      - cooked
      - reply_to_post_number
      - reply_count
      - quote_count
      - deleted_at
      - off_topic_count
      - incoming_link_count
      - bookmark_count
      - score
      - reads
      - post_type
      - sort_order
      - last_editor_id
      - hidden
      - hidden_reason_id
      - notify_moderators_count
      - spam_count
      - illegal_count
      - inappropriate_count
      - last_version_at
      - user_deleted
      - reply_to_user_id
      - percent_rank
      - notify_user_count
      - like_score
      - deleted_by_id
      - edit_reason
      - word_count
      - version
      - cook_method
      - wiki
      - baked_at
      - baked_version
      - hidden_at
      - self_edits
      - reply_quoted
      - via_email
      - raw_email
      - public_version
      - action_code
      - locked_by_id
      - image_upload_id
      - outbound_message_id
      - qa_vote_count   # TODO: added from plugin, maybe skip these automatically for core schema?
    extend:
      - name: reply_to_post_id # NOTE: should this be text??
      - name: original_raw
      - name: upload_ids
        type: json_text
      - name: post_number
        type: integer
      - name: old_relative_url
      - name: accepted_answer
        type: boolean
      - name: small_action
      - name: whisper
        type: boolean
      - name: placeholders
        type: json_text
    indexes:
      - name: posts_by_topic_post_number
        columns: [topic_id, post_number]
  uploads:
    ignore:
      - original_filename  # NOTE: Maybe allow name transforms too??
      - filesize
      - width
      - height
      - url
      - created_at
      - sha1
      - origin
      - retain_hours
      - extension
      - thumbnail_width
      - thumbnail_height
      - etag
      - secure
      - access_control_post_id
      - original_sha1
      - animated
      - verification_status
      - security_last_changed_at
      - security_last_changed_reason
      - dominant_color
    extend:
      - name: filename
        "null": false
      - name: relative_path
      - name: type
      - name: data
        type: blob
  groups:
    include:
      - id
      - name
      - full_name
      - visibility_level
      - members_visibility_level
      - mentionable_level
      - messageable_level
    extend:
      - name: description
  group_members:
    virtual: true
    primary_key: [group_id, user_id]
    extend:
      - name: group_id
        type: integer
      - name: user_id
        type: integer
      - name: owner
        type: boolean
  likes:
    virtual: true
    primary_key: [user_id, post_id]
    extend:
      - name: post_id
        type: integer
        "null": false
      - name: user_id
        type: integer
        "null": false
      - name: created_at
        type: datetime
        "null": false
  # TODO: Pending default values & auto incrementing id column
  user_fields:
    ignore:
      - created_at
      - external_name
      - external_type
    extend:
      - name: options
        type: json_text
  muted_users:
    primary_key: [user_id, muted_user_id]
    ignore:
      - id
      - created_at
  # tags: {}
  # badges: {}
## Schema-wide column configuration options. These options apply to all tables.
## See table specific column configuration options above.
##
## Available Options:
## ignore:  List of core/plugin?? table columns to ignore and exclude from intermidate schema.
columns:
  ignore:
    - updated_at