 /*
 This file is auto-generated from the current state of the Discourse core database schema. Instead
 of editing it directly, please update the `schema.yml` configuration file and re-run the
 `generate_schema` script to update it.
*/

CREATE TABLE badges (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  badge_type_id INTEGER NOT NULL,
  grant_count INTEGER NOT NULL,
  created_at DATETIME NOT NULL,
  allow_title BOOLEAN NOT NULL,
  multiple_grant BOOLEAN NOT NULL,
  icon TEXT,
  listable BOOLEAN,
  target_posts BOOLEAN,
  query TEXT,
  enabled BOOLEAN NOT NULL,
  auto_revoke BOOLEAN NOT NULL,
  badge_grouping_id INTEGER NOT NULL,
  trigger INTEGER,
  show_posts BOOLEAN NOT NULL,
  system BOOLEAN NOT NULL,
  image TEXT,
  long_description TEXT,
  image_upload_id INTEGER
);

CREATE TABLE categories (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  topic_id INTEGER,
  topic_count INTEGER NOT NULL,
  created_at DATETIME NOT NULL,
  user_id INTEGER NOT NULL,
  topics_year INTEGER,
  topics_month INTEGER,
  topics_week INTEGER,
  slug TEXT NOT NULL,
  description TEXT,
  text_color TEXT NOT NULL,
  read_restricted BOOLEAN NOT NULL,
  auto_close_hours FLOAT,
  post_count INTEGER NOT NULL,
  latest_post_id INTEGER,
  latest_topic_id INTEGER,
  position INTEGER,
  parent_category_id INTEGER,
  posts_year INTEGER,
  posts_month INTEGER,
  posts_week INTEGER,
  email_in TEXT,
  email_in_allow_strangers BOOLEAN,
  topics_day INTEGER,
  posts_day INTEGER,
  allow_badges BOOLEAN NOT NULL,
  name_lower TEXT NOT NULL,
  auto_close_based_on_last_post BOOLEAN,
  topic_template TEXT,
  contains_messages BOOLEAN,
  sort_order TEXT,
  sort_ascending BOOLEAN,
  uploaded_logo_id INTEGER,
  uploaded_background_id INTEGER,
  topic_featured_link_allowed BOOLEAN,
  all_topics_wiki BOOLEAN NOT NULL,
  show_subcategory_list BOOLEAN,
  num_featured_topics INTEGER,
  default_view TEXT,
  subcategory_list_style TEXT,
  default_top_period TEXT,
  mailinglist_mirror BOOLEAN NOT NULL,
  minimum_required_tags INTEGER NOT NULL,
  navigate_to_first_post_after_read BOOLEAN NOT NULL,
  search_priority INTEGER,
  allow_global_tags BOOLEAN NOT NULL,
  reviewable_by_group_id INTEGER,
  read_only_banner TEXT,
  default_list_filter TEXT,
  allow_unlimited_owner_edits_on_first_post BOOLEAN NOT NULL,
  default_slow_mode_seconds INTEGER,
  uploaded_logo_dark_id INTEGER,
  uploaded_background_dark_id INTEGER
);

CREATE TABLE groups (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  automatic BOOLEAN NOT NULL,
  user_count INTEGER NOT NULL,
  automatic_membership_email_domains TEXT,
  primary_group BOOLEAN NOT NULL,
  title TEXT,
  grant_trust_level INTEGER,
  incoming_email TEXT,
  has_messages BOOLEAN NOT NULL,
  flair_bg_color TEXT,
  flair_color TEXT,
  bio_raw TEXT,
  bio_cooked TEXT,
  allow_membership_requests BOOLEAN NOT NULL,
  full_name TEXT,
  default_notification_level INTEGER NOT NULL,
  visibility_level INTEGER NOT NULL,
  public_exit BOOLEAN NOT NULL,
  public_admission BOOLEAN NOT NULL,
  membership_request_template TEXT,
  messageable_level INTEGER,
  mentionable_level INTEGER,
  smtp_server TEXT,
  smtp_port INTEGER,
  smtp_ssl BOOLEAN,
  imap_server TEXT,
  imap_port INTEGER,
  imap_ssl BOOLEAN,
  imap_mailbox_name TEXT NOT NULL,
  imap_uid_validity INTEGER NOT NULL,
  imap_last_uid INTEGER NOT NULL,
  email_username TEXT,
  email_password TEXT,
  publish_read_state BOOLEAN NOT NULL,
  members_visibility_level INTEGER NOT NULL,
  imap_last_error TEXT,
  imap_old_emails INTEGER,
  imap_new_emails INTEGER,
  flair_icon TEXT,
  flair_upload_id INTEGER,
  allow_unknown_sender_topic_replies BOOLEAN NOT NULL,
  smtp_enabled BOOLEAN,
  smtp_updated_at DATETIME,
  smtp_updated_by_id INTEGER,
  imap_enabled BOOLEAN,
  imap_updated_at DATETIME,
  imap_updated_by_id INTEGER,
  email_from_alias TEXT
);

CREATE TABLE posts (
  id INTEGER NOT NULL PRIMARY KEY,
  user_id INTEGER,
  topic_id INTEGER NOT NULL,
  post_number INTEGER NOT NULL,
  raw TEXT NOT NULL,
  cooked TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  reply_to_post_number INTEGER,
  reply_count INTEGER NOT NULL,
  quote_count INTEGER NOT NULL,
  deleted_at DATETIME,
  off_topic_count INTEGER NOT NULL,
  like_count INTEGER NOT NULL,
  incoming_link_count INTEGER NOT NULL,
  bookmark_count INTEGER NOT NULL,
  score FLOAT,
  reads INTEGER NOT NULL,
  post_type INTEGER NOT NULL,
  sort_order INTEGER,
  last_editor_id INTEGER,
  hidden BOOLEAN NOT NULL,
  hidden_reason_id INTEGER,
  notify_moderators_count INTEGER NOT NULL,
  spam_count INTEGER NOT NULL,
  illegal_count INTEGER NOT NULL,
  inappropriate_count INTEGER NOT NULL,
  last_version_at DATETIME NOT NULL,
  user_deleted BOOLEAN NOT NULL,
  reply_to_user_id INTEGER,
  percent_rank FLOAT,
  notify_user_count INTEGER NOT NULL,
  like_score INTEGER NOT NULL,
  deleted_by_id INTEGER,
  edit_reason TEXT,
  word_count INTEGER,
  version INTEGER NOT NULL,
  cook_method INTEGER NOT NULL,
  wiki BOOLEAN NOT NULL,
  baked_at DATETIME,
  baked_version INTEGER,
  hidden_at DATETIME,
  self_edits INTEGER NOT NULL,
  reply_quoted BOOLEAN NOT NULL,
  via_email BOOLEAN NOT NULL,
  raw_email TEXT,
  public_version INTEGER NOT NULL,
  action_code TEXT,
  locked_by_id INTEGER,
  image_upload_id INTEGER,
  outbound_message_id TEXT,
  qa_vote_count INTEGER
);

CREATE TABLE tags (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  pm_topic_count INTEGER NOT NULL,
  target_tag_id INTEGER,
  description TEXT,
  public_topic_count INTEGER NOT NULL,
  staff_topic_count INTEGER NOT NULL
);

CREATE TABLE topics (
  id INTEGER NOT NULL PRIMARY KEY,
  title TEXT NOT NULL,
  last_posted_at DATETIME,
  created_at DATETIME NOT NULL,
  views INTEGER NOT NULL,
  posts_count INTEGER NOT NULL,
  user_id INTEGER,
  last_post_user_id INTEGER NOT NULL,
  reply_count INTEGER NOT NULL,
  featured_user1_id INTEGER,
  featured_user2_id INTEGER,
  featured_user3_id INTEGER,
  deleted_at DATETIME,
  highest_post_number INTEGER NOT NULL,
  like_count INTEGER NOT NULL,
  incoming_link_count INTEGER NOT NULL,
  category_id INTEGER,
  visible BOOLEAN NOT NULL,
  moderator_posts_count INTEGER NOT NULL,
  closed BOOLEAN NOT NULL,
  archived BOOLEAN NOT NULL,
  bumped_at DATETIME NOT NULL,
  has_summary BOOLEAN NOT NULL,
  archetype TEXT NOT NULL,
  featured_user4_id INTEGER,
  notify_moderators_count INTEGER NOT NULL,
  spam_count INTEGER NOT NULL,
  pinned_at DATETIME,
  score FLOAT,
  percent_rank FLOAT NOT NULL,
  subtype TEXT,
  slug TEXT,
  deleted_by_id INTEGER,
  participant_count INTEGER,
  word_count INTEGER,
  excerpt TEXT,
  pinned_globally BOOLEAN NOT NULL,
  pinned_until DATETIME,
  fancy_title TEXT,
  highest_staff_post_number INTEGER NOT NULL,
  featured_link TEXT,
  reviewable_score FLOAT NOT NULL,
  image_upload_id INTEGER,
  slow_mode_seconds INTEGER NOT NULL,
  bannered_until DATETIME,
  external_id TEXT
);

CREATE TABLE uploads (
  id INTEGER NOT NULL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  original_filename TEXT NOT NULL,
  filesize INTEGER NOT NULL,
  width INTEGER,
  height INTEGER,
  url TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  sha1 TEXT,
  origin TEXT,
  retain_hours INTEGER,
  extension TEXT,
  thumbnail_width INTEGER,
  thumbnail_height INTEGER,
  etag TEXT,
  secure BOOLEAN NOT NULL,
  access_control_post_id INTEGER,
  original_sha1 TEXT,
  animated BOOLEAN,
  verification_status INTEGER NOT NULL,
  security_last_changed_at DATETIME,
  security_last_changed_reason TEXT,
  dominant_color TEXT
);

CREATE TABLE users (
  username TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  name TEXT,
  seen_notification_id INTEGER NOT NULL,
  last_posted_at DATETIME,
  password_hash TEXT,
  salt TEXT,
  active BOOLEAN NOT NULL,
  last_seen_at DATETIME,
  admin BOOLEAN NOT NULL,
  last_emailed_at DATETIME,
  trust_level INTEGER NOT NULL,
  approved BOOLEAN NOT NULL,
  approved_by_id INTEGER,
  approved_at DATETIME,
  previous_visit_at DATETIME,
  suspended_at DATETIME,
  suspended_till DATETIME,
  date_of_birth DATE,
  views INTEGER NOT NULL,
  flag_level INTEGER NOT NULL,
  ip_address TEXT,
  moderator BOOLEAN,
  title TEXT,
  uploaded_avatar_id INTEGER,
  locale TEXT,
  primary_group_id INTEGER,
  registration_ip_address TEXT,
  staged BOOLEAN NOT NULL,
  first_seen_at DATETIME,
  silenced_till DATETIME,
  group_locked_trust_level INTEGER,
  manual_locked_trust_level INTEGER,
  secure_identifier TEXT,
  flair_group_id INTEGER,
  last_seen_reviewable_id INTEGER,
  bio TEXT,
  email TEXT,
  password TEXT NOT NULL,
  PRIMARY KEY (email, username)
);

CREATE UNIQUE INDEX idx_username ON users (username);
